### ISSUE TITLE
Support node.js?

### ISSUE THREAD

**Issue by wyudong** [ETCDEVTeam/hashicon#23]
Does hashicon support node.js now? There is `document` in `hashicon.cjs.js`, so it won't work for node. I just `require` the package. Any mistakes I've made?

If hashicon can output base64 encoded string of the icon, it will be great.

**Comment by oori** [comment]
Yes, you're right - we planned for node.js support, but we didn't end up doing it all the way through.
That said - it isn't really hard to do.    The easiest solution would be to require `node-canvas` and replace https://github.com/ETCDEVTeam/hashicon/blob/master/src/utils.js#L33 with `createCanvas` from node-canvas.
Although, that would work for both nodejs and browsers, it seems like a heavy addition when our most common use is for browsers.

What if we allow an optional third parameter to the function, like: `hashicon(hash, params, createCanvasFn)`,     then, you'd simply use node-canvas or any other canvas creation utility, as ours is opinionated (_hiDPR retina support_).   I will look into it.

**Comment by wyudong** [comment]
Thanks for the solution! I will try it.

You said your common use is for browsers. What if I want to give every new registered use a random hashicon as avatar? Do you generate it in the browser and then upload to the server?

**Comment by oori** [comment]
> What if I want to give every new registered user a hashicon as avatar? Do you generate it in the browser and then upload to the server?

Currently, the approach is to generate it on the user's browser, not save it on the server at all.    `hashicon(user_key, params)` would be consistent and always produce the same hashicon, and you get Hi-DPR handled (retina display, phones, ..).   also, in a responsive layout, the hashicon could be used in variable sizes, regenerating with `hashicon(key, 100)` or `hashicon(key, {size: 100});` would look much better then resizing an image from the server.

Still, I agree we need to make it work with backend (node-canvas, as I described above), we'll do it soon enough (or some PR...)

**Comment by oori** [comment]
Resolved in v0.3.0
https://github.com/ETCDEVTeam/hashicon/pull/27#issuecomment-521486160
